export const CHANGE_ALL_CHECK_ON = 'CHANGE_CHECK_ON';
export const CHANGE_ALL_CHECK_OFF = 'CHANGE_CHECK_OFF';
export const CHANGE_ONE_CHECK_ON = 'CHANGE_ONE_CHECK_ON';
export const CHANGE_MAIN_CHECK_OFF = 'CHANGE_MAIN_CHECK_OFF';

export const GET_All_TICKETS = 'GET_All_TICKETS';
export const GET_CHEAP_TICKETS = 'GET_CHEAP_TICKETS';
export const GET_FAST_TICKETS = 'GET_FAST_TICKETS';

export const ERROR_HANDLING = 'ERROR_HANDLING';