export const CHANGE_ALL_CHECK_ON = 'CHANGE_CHECK_ON';
export const CHANGE_ALL_CHECK_OFF = 'CHANGE_CHECK_OFF';
export const CHANGE_ONE_CHECK_ON = 'CHANGE_ONE_CHECK_ON';
export const CHANGE_MAIN_CHECK_OFF = 'CHANGE_MAIN_CHECK_OFF';